apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: my-app
  namespace: prod
spec:
  components:
    - name: my-app
      type: webservice
      properties:
        image: docker.io/taweizhong235/nginx-test:master-abc123-555555 # {"$imagepolicy": "prod:image-gitops"}
