apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: my-app
  namespace: prod
spec:
  components:
    - name: my-app
      type: webservice
      properties:
        image: nginx # {"$imagepolicy": "prod:image-gitops"}
